### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by cydstumpel** [soraya2/minor-wafs#2]
![screenshot 2017-02-10 12 58 16](https://cloud.githubusercontent.com/assets/14167636/22826047/a695a02e-ef90-11e6-9ff9-bdce9702c3e7.png)
This is pretty cumbersome, you could use a queryselector and use the parameter 'route' to get the section & remove the class.

Your code looks clean and well commented! :)

**Comment by soraya2** [comment]
i am using the route parameter here all ready because i'm calling the toggle function with that parameter.
